#include "ctagSoundProcessorDrumRackDS.hpp"

using namespace CTAG::SP;

// TODOs: fx return before compressor, stereo panning with delay -> when panned right, levels are lower, metallic sound of reverb.

void ctagSoundProcessorDrumRackDS::Process(const ProcessData& data){
    const float maxFXSendLevelDly {4.f};
    const float maxFXSendLevelRev {2.f};

    // Digital Snare Drum
    MK_BOOL_PAR(bDSMute, ds_mute)
    MK_BOOL_PAR(bDSTrig, ds_trigger)
    if (bDSTrig != dsd_trig_prev){
        dsd_trig_prev = bDSTrig;
    }
    else{
        bDSTrig = false;
    }

    MK_FLT_PAR_ABS(fDSLev, ds_lev, 4095.f, 2.f)
    fDSLev *= fDSLev;
    MK_FLT_PAR_ABS_PAN(fDSPan, ds_pan, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fDSFX1Send, ds_fx1, 4095.f, maxFXSendLevelDly)
    fDSFX1Send *= fDSFX1Send;
    MK_FLT_PAR_ABS(fDSFX2Send, ds_fx2, 4095.f, maxFXSendLevelRev)
    fDSFX2Send *= fDSFX2Send;

    if (bDSMute || fDSLev < 0.0001f)    {
        memset(data.buf, 0, 32 * sizeof(float));
        return;
    }


    MK_FLT_PAR_ABS(fDSAccent, ds_accent, 4095.f, 1.f)
    MK_FLT_PAR_ABS_MIN_MAX(fDSF0, ds_f0, 4095.f, 0.0008f, 0.01f)
    MK_FLT_PAR_ABS(fDSFmAmt, ds_fm_amt, 4095.f, 1.5f)
    MK_FLT_PAR_ABS(fDSDecay, ds_decay, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fDSSpy, ds_spy, 4095.f, 1.f)
    dsd.Render(
        false,
        bDSTrig,
        fDSAccent,
        fDSF0,
        fDSFmAmt,
        fDSDecay,
        fDSSpy,
        dsd_out,
        32);

    float lev_l = (1.f - fDSPan) * fDSLev;
    float lev_r = fDSPan * fDSLev;

    for (int i = 0; i < 32; i++) {
        data.buf[i * 2 + 0] = dsd_out[i] * lev_l;
        data.buf[i * 2 + 1] = dsd_out[i] * lev_r;
    }

    if (fDSFX1Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus1[i * 2 + 0] += dsd_out[i] * lev_l * fDSFX1Send;
            data.fxbus1[i * 2 + 1] += dsd_out[i] * lev_r * fDSFX1Send;
        }
    }

    if (fDSFX2Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus2[i * 2 + 0] += dsd_out[i] * lev_l * fDSFX2Send;
            data.fxbus2[i * 2 + 1] += dsd_out[i] * lev_r * fDSFX2Send;
        }
    }
}

void ctagSoundProcessorDrumRackDS::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    dsd.Init();

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorDrumRackDS::~ctagSoundProcessorDrumRackDS(){
    // no explicit freeing for blockMem needed, done by ctagSPAllocator
    // explicit free is only needed when using heap_caps_malloc() with MALLOC_CAPS_SPIRAM
}

void ctagSoundProcessorDrumRackDS::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("ds_trigger", [&](const int val){ ds_trigger = val;});
	pMapTrig.emplace("ds_trigger", [&](const int val){ trig_ds_trigger = val;});
	pMapPar.emplace("ds_mute", [&](const int val){ ds_mute = val;});
	pMapTrig.emplace("ds_mute", [&](const int val){ trig_ds_mute = val;});
	pMapPar.emplace("ds_lev", [&](const int val){ ds_lev = val;});
	pMapCv.emplace("ds_lev", [&](const int val){ cv_ds_lev = val;});
	pMapPar.emplace("ds_pan", [&](const int val){ ds_pan = val;});
	pMapCv.emplace("ds_pan", [&](const int val){ cv_ds_pan = val;});
	pMapPar.emplace("ds_fx1", [&](const int val){ ds_fx1 = val;});
	pMapCv.emplace("ds_fx1", [&](const int val){ cv_ds_fx1 = val;});
	pMapPar.emplace("ds_fx2", [&](const int val){ ds_fx2 = val;});
	pMapCv.emplace("ds_fx2", [&](const int val){ cv_ds_fx2 = val;});
	pMapPar.emplace("ds_accent", [&](const int val){ ds_accent = val;});
	pMapCv.emplace("ds_accent", [&](const int val){ cv_ds_accent = val;});
	pMapPar.emplace("ds_f0", [&](const int val){ ds_f0 = val;});
	pMapCv.emplace("ds_f0", [&](const int val){ cv_ds_f0 = val;});
	pMapPar.emplace("ds_fm_amt", [&](const int val){ ds_fm_amt = val;});
	pMapCv.emplace("ds_fm_amt", [&](const int val){ cv_ds_fm_amt = val;});
	pMapPar.emplace("ds_decay", [&](const int val){ ds_decay = val;});
	pMapCv.emplace("ds_decay", [&](const int val){ cv_ds_decay = val;});
	pMapPar.emplace("ds_spy", [&](const int val){ ds_spy = val;});
	pMapCv.emplace("ds_spy", [&](const int val){ cv_ds_spy = val;});
	isStereo = false;
	id = "DrumRackDS";
	// sectionCpp0
}
