#include "ctagSoundProcessorDrumRackDB.hpp"

using namespace CTAG::SP;

// TODOs: fx return before compressor, stereo panning with delay -> when panned right, levels are lower, metallic sound of reverb.

void ctagSoundProcessorDrumRackDB::Process(const ProcessData& data){
    const float maxFXSendLevelDly {4.f};
    const float maxFXSendLevelRev {2.f};
    

    // Digital Bass Drum
    MK_BOOL_PAR(bDBMute, db_mute)
    MK_BOOL_PAR(bDBTrig, db_trigger)
    if (bDBTrig != dbd_trig_prev){
        dbd_trig_prev = bDBTrig;
    }
    else{
        bDBTrig = false;
    }

    MK_FLT_PAR_ABS(fDBLev, db_lev, 4095.f, 2.f)
    fDBLev *= fDBLev;
    MK_FLT_PAR_ABS_PAN(fDBPan, db_pan, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fDBFX1Send, db_fx1, 4095.f, maxFXSendLevelDly)
    fDBFX1Send *= fDBFX1Send;
    MK_FLT_PAR_ABS(fDBFX2Send, db_fx2, 4095.f, maxFXSendLevelRev)
    fDBFX2Send *= fDBFX2Send;

    if (bDBMute || fDBLev < 0.0001f) {
        memset(data.buf, 0, 32 * sizeof(float));
        return;
    }

    MK_FLT_PAR_ABS(fDBAccent, db_accent, 4095.f, 1.f)
    MK_FLT_PAR_ABS_MIN_MAX(fDBF0, db_f0, 4095.f, 0.0005f, 0.01f)
    MK_FLT_PAR_ABS(fDBTone, db_tone, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fDBDecay, db_decay, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fDBDirty, db_dirty, 4095.f, 5.f)
    MK_FLT_PAR_ABS(fDBFmEnv, db_fm_env, 4095.f, 5.f)
    MK_FLT_PAR_ABS(fDBFmDcy, db_fm_dcy, 4095.f, 4.f)
    dbd.Render(
        false,
        bDBTrig,
        fDBAccent,
        fDBF0,
        fDBTone,
        fDBDecay,
        fDBDirty,
        fDBFmEnv,
        fDBFmDcy,
        dbd_out,
        32);

    float lev_l = (1.f - fDBPan) * fDBLev;
    float lev_r = fDBPan * fDBLev;

    for (int i = 0; i < 32; i++) {
        data.buf[i * 2 + 0] = dbd_out[i] * lev_l;
        data.buf[i * 2 + 1] = dbd_out[i] * lev_r;
    }

    if (fDBFX1Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus1[i * 2 + 0] += dbd_out[i] * lev_l * fDBFX1Send;
            data.fxbus1[i * 2 + 1] += dbd_out[i] * lev_r * fDBFX1Send;
        }
    }

    if (fDBFX2Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus2[i * 2 + 0] += dbd_out[i] * lev_l * fDBFX2Send;
            data.fxbus2[i * 2 + 1] += dbd_out[i] * lev_r * fDBFX2Send;
        }
    }
}

void ctagSoundProcessorDrumRackDB::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    dbd.Init();

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorDrumRackDB::~ctagSoundProcessorDrumRackDB(){
    // no explicit freeing for blockMem needed, done by ctagSPAllocator
    // explicit free is only needed when using heap_caps_malloc() with MALLOC_CAPS_SPIRAM
}

void ctagSoundProcessorDrumRackDB::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("db_trigger", [&](const int val){ db_trigger = val;});
	pMapTrig.emplace("db_trigger", [&](const int val){ trig_db_trigger = val;});
	pMapPar.emplace("db_mute", [&](const int val){ db_mute = val;});
	pMapTrig.emplace("db_mute", [&](const int val){ trig_db_mute = val;});
	pMapPar.emplace("db_lev", [&](const int val){ db_lev = val;});
	pMapCv.emplace("db_lev", [&](const int val){ cv_db_lev = val;});
	pMapPar.emplace("db_pan", [&](const int val){ db_pan = val;});
	pMapCv.emplace("db_pan", [&](const int val){ cv_db_pan = val;});
	pMapPar.emplace("db_fx1", [&](const int val){ db_fx1 = val;});
	pMapCv.emplace("db_fx1", [&](const int val){ cv_db_fx1 = val;});
	pMapPar.emplace("db_fx2", [&](const int val){ db_fx2 = val;});
	pMapCv.emplace("db_fx2", [&](const int val){ cv_db_fx2 = val;});
	pMapPar.emplace("db_accent", [&](const int val){ db_accent = val;});
	pMapCv.emplace("db_accent", [&](const int val){ cv_db_accent = val;});
	pMapPar.emplace("db_f0", [&](const int val){ db_f0 = val;});
	pMapCv.emplace("db_f0", [&](const int val){ cv_db_f0 = val;});
	pMapPar.emplace("db_tone", [&](const int val){ db_tone = val;});
	pMapCv.emplace("db_tone", [&](const int val){ cv_db_tone = val;});
	pMapPar.emplace("db_decay", [&](const int val){ db_decay = val;});
	pMapCv.emplace("db_decay", [&](const int val){ cv_db_decay = val;});
	pMapPar.emplace("db_dirty", [&](const int val){ db_dirty = val;});
	pMapCv.emplace("db_dirty", [&](const int val){ cv_db_dirty = val;});
	pMapPar.emplace("db_fm_env", [&](const int val){ db_fm_env = val;});
	pMapCv.emplace("db_fm_env", [&](const int val){ cv_db_fm_env = val;});
	pMapPar.emplace("db_fm_dcy", [&](const int val){ db_fm_dcy = val;});
	pMapCv.emplace("db_fm_dcy", [&](const int val){ cv_db_fm_dcy = val;});
	isStereo = true;
	id = "DrumRackDB";
	// sectionCpp0
}
