#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackSampler : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init() override;
            virtual ~ctagSoundProcessorDrumRackSampler();

        private:
            virtual void knowYourself() override;

            float s1_out[32];
        	float silence[32];
            CTAG::SYNTHESIS::RomplerVoiceMinimal rompler[1];
            CTAG::SP::HELPERS::ctagSampleRom sampleRom;

            // private attributes could go here
            // autogenerated code here
            // sectionHpp 
            atomic<int32_t> s1_gate, trig_s1_gate;
            atomic<int32_t> s1_mute, trig_s1_mute;
            atomic<int32_t> s1_lev, cv_s1_lev;
            atomic<int32_t> s1_pan, cv_s1_pan;
            atomic<int32_t> s1_fx1, cv_s1_fx1;
            atomic<int32_t> s1_fx2, cv_s1_fx2;
            atomic<int32_t> s1_speed, cv_s1_speed;
            atomic<int32_t> s1_pitch, cv_s1_pitch;
            atomic<int32_t> s1_bank, cv_s1_bank;
            atomic<int32_t> s1_slice, cv_s1_slice;
            atomic<int32_t> s1_start, cv_s1_start;
            atomic<int32_t> s1_end, cv_s1_end;
            atomic<int32_t> s1_lp, trig_s1_lp;
            atomic<int32_t> s1_lp_pp, trig_s1_lp_pp;
            atomic<int32_t> s1_lp_pos, cv_s1_lp_pos;
            atomic<int32_t> s1_atk, cv_s1_atk;
            atomic<int32_t> s1_dcy, cv_s1_dcy;
            atomic<int32_t> s1_eg2fm, cv_s1_eg2fm;
            atomic<int32_t> s1_brr, cv_s1_brr;
            atomic<int32_t> s1_ft, cv_s1_ft;
            atomic<int32_t> s1_fc, cv_s1_fc;
            atomic<int32_t> s1_fq, cv_s1_fq;
            // sectionHpp
        };
    }
}

