#include "ctagSoundProcessorDrumRackFMB.hpp"

using namespace CTAG::SP;

// TODOs: fx return before compressor, stereo panning with delay -> when panned right, levels are lower, metallic sound of reverb.

void ctagSoundProcessorDrumRackFMB::Process(const ProcessData& data){
    const float maxFXSendLevelDly {4.f};
    const float maxFXSendLevelRev {2.f};
    
	// FM Bass Drum
    MK_BOOL_PAR(bFMBMute, fmb_mute)
    MK_BOOL_PAR(bFMBTrig, fmb_trigger)
    if (bFMBTrig != fmb_trig_prev && bFMBTrig){
	    fmb_trig_prev = true;
	    fmb.Trigger();
    }
    else if (!bFMBTrig){
	    fmb_trig_prev = false;
    }

    MK_FLT_PAR_ABS(fFMBLev, fmb_lev, 4095.f, 2.f)
    fFMBLev *= fFMBLev;
    MK_FLT_PAR_ABS_PAN(fFMBPan, fmb_pan, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fFMBFX1Send, fmb_fx1, 4095.f, maxFXSendLevelDly)
    fFMBFX1Send *= fFMBFX1Send;
    MK_FLT_PAR_ABS(fFMBFX2Send, fmb_fx2, 4095.f, maxFXSendLevelRev)
    fFMBFX2Send *= fFMBFX2Send;

    if (bFMBMute || fFMBLev < 0.0001f) {
        memset(data.buf, 0, 32 * sizeof(float));
        return;
    }
	 
    MK_BOOL_PAR(bFMBUseRatioMode, fmb_use_ratio_mode)
    MK_BOOL_PAR(bFMBModEnvSync, fmb_mod_env_sync)
    float fFMBF0 = fmb_f_b/4095.f * (200.f-20.f)+20.f;
    if(cv_fmb_f_b != -1){
        float fMod = data.cv[cv_fmb_f_b] * 5.f;
        fMod = CTAG::SP::HELPERS::fastpow2(fMod);
        fFMBF0 *= fMod;
    }
    MK_FLT_PAR_ABS_MIN_MAX(fFMBDecayBase, fmb_d_b, 4095.f, 0.001f, 1.f)
    MK_FLT_PAR_ABS_MIN_MAX(fFMBFMod, fmb_f_m, 4095.f, 40.f, 2000.f)
    MK_FLT_PAR_ABS(fFMBRatioModIndex, fmb_f_m, 4095.f, 63.f)
    int iModIndex = static_cast<int>(fFMBRatioModIndex);
    CONSTRAIN(iModIndex, 0, 63)
    MK_FLT_PAR_ABS_MIN_MAX(fFMBI, fmb_I, 4095.f, 0.f, 10.f)
    MK_FLT_PAR_ABS_MIN_MAX(fFMBDecayMod, fmb_d_m, 4095.f, 0.001f, .5f)
    MK_INT_PAR(iModFeedback, fmb_b_m, 16.f)
    MK_FLT_PAR_ABS_MIN_MAX(fFMBAmpFreq, fmb_A_f, 4095.f, 0.f, 1000.f)
    MK_FLT_PAR_ABS_MIN_MAX(fFMBDecayFreq, fmb_d_f, 4095.f, 0.001f, .1f)

    fmb.params.use_ratio_mode = bFMBUseRatioMode;
    fmb.params.mod_env_sync = bFMBModEnvSync;
    fmb.params.f_b = fFMBF0;
    fmb.params.d_b = fFMBDecayBase;
    fmb.params.f_m = fFMBFMod;
    fmb.params.mod_ratio_index = iModIndex;
    fmb.params.I = fFMBI;
    fmb.params.d_m = fFMBDecayMod;
    fmb.params.b_m = static_cast<float>(iModFeedback);
    fmb.params.A_f = fFMBAmpFreq;
    fmb.params.d_f = fFMBDecayFreq;

    fmb.Process(fmb_out, 32);

    float lev_l = (1.f - fFMBPan) * fFMBLev;
    float lev_r = fFMBPan * fFMBLev;

    for (int i = 0; i < 32; i++) {
        data.buf[i * 2 + 0] = fmb_out[i] * lev_l;
        data.buf[i * 2 + 1] = fmb_out[i] * lev_r;
    }

    if (fFMBFX1Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus1[i * 2 + 0] += fmb_out[i] * lev_l * fFMBFX1Send;
            data.fxbus1[i * 2 + 1] += fmb_out[i] * lev_r * fFMBFX1Send;
        }
    }

    if (fFMBFX2Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus2[i * 2 + 0] += fmb_out[i] * lev_l * fFMBFX2Send;
            data.fxbus2[i * 2 + 1] += fmb_out[i] * lev_r * fFMBFX2Send;
        }
    }
}

void ctagSoundProcessorDrumRackFMB::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    fmb.Init();

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorDrumRackFMB::~ctagSoundProcessorDrumRackFMB(){
    // no explicit freeing for blockMem needed, done by ctagSPAllocator
    // explicit free is only needed when using heap_caps_malloc() with MALLOC_CAPS_SPIRAM
}

void ctagSoundProcessorDrumRackFMB::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("fmb_trigger", [&](const int val){ fmb_trigger = val;});
	pMapTrig.emplace("fmb_trigger", [&](const int val){ trig_fmb_trigger = val;});
	pMapPar.emplace("fmb_mute", [&](const int val){ fmb_mute = val;});
	pMapTrig.emplace("fmb_mute", [&](const int val){ trig_fmb_mute = val;});
	pMapPar.emplace("fmb_lev", [&](const int val){ fmb_lev = val;});
	pMapCv.emplace("fmb_lev", [&](const int val){ cv_fmb_lev = val;});
	pMapPar.emplace("fmb_pan", [&](const int val){ fmb_pan = val;});
	pMapCv.emplace("fmb_pan", [&](const int val){ cv_fmb_pan = val;});
	pMapPar.emplace("fmb_fx1", [&](const int val){ fmb_fx1 = val;});
	pMapCv.emplace("fmb_fx1", [&](const int val){ cv_fmb_fx1 = val;});
	pMapPar.emplace("fmb_fx2", [&](const int val){ fmb_fx2 = val;});
	pMapCv.emplace("fmb_fx2", [&](const int val){ cv_fmb_fx2 = val;});
	pMapPar.emplace("fmb_use_ratio_mode", [&](const int val){ fmb_use_ratio_mode = val;});
	pMapTrig.emplace("fmb_use_ratio_mode", [&](const int val){ trig_fmb_use_ratio_mode = val;});
	pMapPar.emplace("fmb_mod_env_sync", [&](const int val){ fmb_mod_env_sync = val;});
	pMapTrig.emplace("fmb_mod_env_sync", [&](const int val){ trig_fmb_mod_env_sync = val;});
	pMapPar.emplace("fmb_f_b", [&](const int val){ fmb_f_b = val;});
	pMapCv.emplace("fmb_f_b", [&](const int val){ cv_fmb_f_b = val;});
	pMapPar.emplace("fmb_d_b", [&](const int val){ fmb_d_b = val;});
	pMapCv.emplace("fmb_d_b", [&](const int val){ cv_fmb_d_b = val;});
	pMapPar.emplace("fmb_f_m", [&](const int val){ fmb_f_m = val;});
	pMapCv.emplace("fmb_f_m", [&](const int val){ cv_fmb_f_m = val;});
	pMapPar.emplace("fmb_I", [&](const int val){ fmb_I = val;});
	pMapCv.emplace("fmb_I", [&](const int val){ cv_fmb_I = val;});
	pMapPar.emplace("fmb_d_m", [&](const int val){ fmb_d_m = val;});
	pMapCv.emplace("fmb_d_m", [&](const int val){ cv_fmb_d_m = val;});
	pMapPar.emplace("fmb_b_m", [&](const int val){ fmb_b_m = val;});
	pMapCv.emplace("fmb_b_m", [&](const int val){ cv_fmb_b_m = val;});
	pMapPar.emplace("fmb_A_f", [&](const int val){ fmb_A_f = val;});
	pMapCv.emplace("fmb_A_f", [&](const int val){ cv_fmb_A_f = val;});
	pMapPar.emplace("fmb_d_f", [&](const int val){ fmb_d_f = val;});
	pMapCv.emplace("fmb_d_f", [&](const int val){ cv_fmb_d_f = val;});
	isStereo = true;
	id = "DrumRackFMB";
	// sectionCpp0
}
