#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackAS : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init() override;
            virtual ~ctagSoundProcessorDrumRackAS();

        private:
            virtual void knowYourself() override;

            plaits::AnalogSnareDrum asd;
            float asd_out[32];
            bool asd_trig_prev {false};

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
            atomic<int32_t> as_trigger, trig_as_trigger;
            atomic<int32_t> as_mute, trig_as_mute;
            atomic<int32_t> as_lev, cv_as_lev;
            atomic<int32_t> as_pan, cv_as_pan;
            atomic<int32_t> as_fx1, cv_as_fx1;
            atomic<int32_t> as_fx2, cv_as_fx2;
            atomic<int32_t> as_accent, cv_as_accent;
            atomic<int32_t> as_f0, cv_as_f0;
            atomic<int32_t> as_tone, cv_as_tone;
            atomic<int32_t> as_decay, cv_as_decay;
            atomic<int32_t> as_a_spy, cv_as_a_spy;
            // sectionHpp
        };
    }
}

