#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackCL : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init() override;
            virtual ~ctagSoundProcessorDrumRackCL();

        private:
            virtual void knowYourself() override;

            CTAG::SYNTHESIS::Clap cl;
        	float cl_out[32];
        	bool cl_trig_prev {false};

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
            atomic<int32_t> cl_trigger, trig_cl_trigger;
            atomic<int32_t> cl_mute, trig_cl_mute;
            atomic<int32_t> cl_lev, cv_cl_lev;
            atomic<int32_t> cl_pan, cv_cl_pan;
            atomic<int32_t> cl_fx1, cv_cl_fx1;
            atomic<int32_t> cl_fx2, cv_cl_fx2;
            atomic<int32_t> cl_f0, cv_cl_f0;
            atomic<int32_t> cl_tone, cv_cl_tone;
            atomic<int32_t> cl_decay, cv_cl_decay;
            atomic<int32_t> cl_scale, cv_cl_scale;
            atomic<int32_t> cl_transient, cv_cl_transient;
            // sectionHpp
        };
    }
}

