#include "ctagSoundProcessorDrumRackRS.hpp"

using namespace CTAG::SP;

// TODOs: fx return before compressor, stereo panning with delay -> when panned right, levels are lower, metallic sound of reverb.

void ctagSoundProcessorDrumRackRS::Process(const ProcessData& data){
    const float maxFXSendLevelDly {4.f};
    const float maxFXSendLevelRev {2.f};
  
    // rimshot

    MK_BOOL_PAR(bRSMute, rs_mute)
    MK_FLT_PAR_ABS(fRSLev, rs_lev, 4095.f, 2.f)
    fRSLev *= fRSLev;
    MK_FLT_PAR_ABS_PAN(fRSPan, rs_pan, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fRSFX1Send, rs_fx1, 4095.f, maxFXSendLevelDly)
    fRSFX1Send *= fRSFX1Send;
    MK_FLT_PAR_ABS(fRSFX2Send, rs_fx2, 4095.f, maxFXSendLevelRev)
    fRSFX2Send *= fRSFX2Send;

    if (bRSMute || fRSLev < 0.0001f) {
        memset(data.buf, 0, 32 * 2 * sizeof(float));
        return;
    }

    MK_FLT_PAR_ABS_MIN_MAX(rs_f0_, rs_f0, 4095.f, 70.f, 350.f)
    MK_FLT_PAR_ABS_MIN_MAX(rs_decay_, rs_decay, 4095.f, .1f, .75f)
    MK_FLT_PAR_ABS_MIN_MAX(rs_noise_, rs_noise, 4095.f, 0.f, .2f)
    MK_FLT_PAR_ABS_MIN_MAX(rs_accent_, rs_accent, 4095.f, 0.1f, 1.f)
    MK_FLT_PAR_ABS_MIN_MAX(rs_base_, rs_tone, 4095.f, .35f, .65f)
    MK_FLT_PAR_ABS_MIN_MAX(rs_reso_hp_, rs_tone, 4095.f, 5.f, 1.f)

    rs.params.f0 = rs_f0_ / 44100.f;
    rs.params.decay = rs_decay_;
    rs.params.accent = rs_accent_;
    rs.params.reso_hp = rs_reso_hp_;
    rs.params.base = rs_base_;
    rs.params.noise_level = rs_noise_;

    MK_BOOL_PAR(bRSTrig, rs_trigger)
    if (bRSTrig != rs_trig_prev && bRSTrig){
        rs_trig_prev = true;
        rs.Trigger();
    }
    else if (!bRSTrig){
        rs_trig_prev = false;
    }

    rs.Process(rs_out, 32);

    float lev_l = (1.f - fRSPan) * fRSLev;
    float lev_r = fRSPan * fRSLev;

    for (int i = 0; i < 32; i++) {
        data.buf[i * 2 + 0] = rs_out[i] * lev_l;
        data.buf[i * 2 + 1] = rs_out[i] * lev_r;
    }

    if (fRSFX1Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus1[i * 2 + 0] += rs_out[i] * lev_l * fRSFX1Send;
            data.fxbus1[i * 2 + 1] += rs_out[i] * lev_r * fRSFX1Send;
        }
    }

    if (fRSFX2Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus2[i * 2 + 0] += rs_out[i] * lev_l * fRSFX2Send;
            data.fxbus2[i * 2 + 1] += rs_out[i] * lev_r * fRSFX2Send;
        }
    }
}

void ctagSoundProcessorDrumRackRS::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    rs.Init();

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorDrumRackRS::~ctagSoundProcessorDrumRackRS(){
    // no explicit freeing for blockMem needed, done by ctagSPAllocator
    // explicit free is only needed when using heap_caps_malloc() with MALLOC_CAPS_SPIRAM
}

void ctagSoundProcessorDrumRackRS::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("rs_trigger", [&](const int val){ rs_trigger = val;});
	pMapTrig.emplace("rs_trigger", [&](const int val){ trig_rs_trigger = val;});
	pMapPar.emplace("rs_mute", [&](const int val){ rs_mute = val;});
	pMapTrig.emplace("rs_mute", [&](const int val){ trig_rs_mute = val;});
	// pMapPar.emplace("rs_lev", [&](const int val){ rs_lev = val;});
	// pMapCv.emplace("rs_lev", [&](const int val){ cv_rs_lev = val;});
	// pMapPar.emplace("rs_pan", [&](const int val){ rs_pan = val;});
	// pMapCv.emplace("rs_pan", [&](const int val){ cv_rs_pan = val;});
	// pMapPar.emplace("rs_fx1", [&](const int val){ rs_fx1 = val;});
	// pMapCv.emplace("rs_fx1", [&](const int val){ cv_rs_fx1 = val;});
	// pMapPar.emplace("rs_fx2", [&](const int val){ rs_fx2 = val;});
	// pMapCv.emplace("rs_fx2", [&](const int val){ cv_rs_fx2 = val;});
	pMapPar.emplace("rs_accent", [&](const int val){ rs_accent = val;});
	pMapCv.emplace("rs_accent", [&](const int val){ cv_rs_accent = val;});
	pMapPar.emplace("rs_f0", [&](const int val){ rs_f0 = val;});
	pMapCv.emplace("rs_f0", [&](const int val){ cv_rs_f0 = val;});
	pMapPar.emplace("rs_tone", [&](const int val){ rs_tone = val;});
	pMapCv.emplace("rs_tone", [&](const int val){ cv_rs_tone = val;});
	pMapPar.emplace("rs_decay", [&](const int val){ rs_decay = val;});
	pMapCv.emplace("rs_decay", [&](const int val){ cv_rs_decay = val;});
	pMapPar.emplace("rs_noise", [&](const int val){ rs_noise = val;});
	pMapCv.emplace("rs_noise", [&](const int val){ cv_rs_noise = val;});
	isStereo = true;
	id = "DrumRackRS";
	// sectionCpp0
}
