#include "ctagSoundProcessorDrumRackAS.hpp"

using namespace CTAG::SP;

void ctagSoundProcessorDrumRackAS::Process(const ProcessData& data){
    const float maxFXSendLevelDly {4.f};
    const float maxFXSendLevelRev {2.f};

    // Analog Snare Drum
    MK_BOOL_PAR(bASMute, as_mute)
    MK_BOOL_PAR(bASTrig, as_trigger)
    if (bASTrig != asd_trig_prev){
        asd_trig_prev = bASTrig;
    }
    else{
        bASTrig = false;
    }

    MK_FLT_PAR_ABS(fASLev, as_lev, 4095.f, 2.f)
    fASLev *= fASLev;
    MK_FLT_PAR_ABS_PAN(fASPan, as_pan, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fASFX1Send, as_fx1, 4095.f, maxFXSendLevelDly)
    fASFX1Send *= fASFX1Send;
    MK_FLT_PAR_ABS(fASFX2Send, as_fx2, 4095.f, maxFXSendLevelRev)
    fASFX2Send *= fASFX2Send;

    if (bASMute || fASLev < 0.0001f) {
        memset(data.buf, 0, 32 * sizeof(float));
        return;
    }

    MK_FLT_PAR_ABS(fASAccent, as_accent, 4095.f, 1.f)
    MK_FLT_PAR_ABS_MIN_MAX(fASF0, as_f0, 4095.f, 0.001f, 0.01f)
    MK_FLT_PAR_ABS(fASTone, as_tone, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fASDecay, as_decay, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fASAspy, as_a_spy, 4095.f, 1.f)
    asd.Render(
        false,
        bASTrig,
        fASAccent,
        fASF0,
        fASTone,
        fASDecay,
        fASAspy,
        asd_out,
        32);

    float lev_l = (1.f - fASPan) * fASLev;
    float lev_r = fASPan * fASLev;

    for (int i = 0; i < 32; i++) {
        data.buf[i * 2 + 0] = asd_out[i] * lev_l;
        data.buf[i * 2 + 1] = asd_out[i] * lev_r;
    }

    if (fASFX1Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus1[i * 2 + 0] += asd_out[i] * lev_l * fASFX1Send;
            data.fxbus1[i * 2 + 1] += asd_out[i] * lev_r * fASFX1Send;
        }
    }

    if (fASFX2Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus2[i * 2 + 0] += asd_out[i] * lev_l * fASFX2Send;
            data.fxbus2[i * 2 + 1] += asd_out[i] * lev_r * fASFX2Send;
        }
    }
}

void ctagSoundProcessorDrumRackAS::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    asd.Init();

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorDrumRackAS::~ctagSoundProcessorDrumRackAS(){
    // no explicit freeing for blockMem needed, done by ctagSPAllocator
    // explicit free is only needed when using heap_caps_malloc() with MALLOC_CAPS_SPIRAM
}

void ctagSoundProcessorDrumRackAS::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("as_trigger", [&](const int val){ as_trigger = val;});
	pMapTrig.emplace("as_trigger", [&](const int val){ trig_as_trigger = val;});
	pMapPar.emplace("as_mute", [&](const int val){ as_mute = val;});
	pMapTrig.emplace("as_mute", [&](const int val){ trig_as_mute = val;});
	pMapPar.emplace("as_lev", [&](const int val){ as_lev = val;});
	pMapCv.emplace("as_lev", [&](const int val){ cv_as_lev = val;});
	pMapPar.emplace("as_pan", [&](const int val){ as_pan = val;});
	pMapCv.emplace("as_pan", [&](const int val){ cv_as_pan = val;});
	pMapPar.emplace("as_fx1", [&](const int val){ as_fx1 = val;});
	pMapCv.emplace("as_fx1", [&](const int val){ cv_as_fx1 = val;});
	pMapPar.emplace("as_fx2", [&](const int val){ as_fx2 = val;});
	pMapCv.emplace("as_fx2", [&](const int val){ cv_as_fx2 = val;});
	pMapPar.emplace("as_accent", [&](const int val){ as_accent = val;});
	pMapCv.emplace("as_accent", [&](const int val){ cv_as_accent = val;});
	pMapPar.emplace("as_f0", [&](const int val){ as_f0 = val;});
	pMapCv.emplace("as_f0", [&](const int val){ cv_as_f0 = val;});
	pMapPar.emplace("as_tone", [&](const int val){ as_tone = val;});
	pMapCv.emplace("as_tone", [&](const int val){ cv_as_tone = val;});
	pMapPar.emplace("as_decay", [&](const int val){ as_decay = val;});
	pMapCv.emplace("as_decay", [&](const int val){ cv_as_decay = val;});
	pMapPar.emplace("as_a_spy", [&](const int val){ as_a_spy = val;});
	pMapCv.emplace("as_a_spy", [&](const int val){ cv_as_a_spy = val;});
	isStereo = false;
	id = "DrumRackAS";
	// sectionCpp0
}
