#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackHH1 : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init(std::size_t blockSize, void *blockPtr) override;
            virtual ~ctagSoundProcessorDrumRackHH1();

        private:
            virtual void knowYourself() override;

            plaits::HiHat<plaits::SquareNoise, plaits::SwingVCA, true, false> hh1;
            float hh1_out[32];
            float temp1_[32];
            float temp2_[32];
        	float silence[32];
            bool hh1_trig_prev {false};

            // rompler
            CTAG::SYNTHESIS::RomplerVoiceMinimal rompler[4];
            CTAG::SP::HELPERS::ctagSampleRom sampleRom;


            // private attributes could go here
            // autogenerated code here
            // sectionHpp
            atomic<int32_t> hh1_trigger, trig_hh1_trigger;
            atomic<int32_t> hh1_mute, trig_hh1_mute;
            atomic<int32_t> hh1_lev, cv_hh1_lev;
            atomic<int32_t> hh1_pan, cv_hh1_pan;
            atomic<int32_t> hh1_fx1, cv_hh1_fx1;
            atomic<int32_t> hh1_fx2, cv_hh1_fx2;
            atomic<int32_t> hh1_accent, cv_hh1_accent;
            atomic<int32_t> hh1_f0, cv_hh1_f0;
            atomic<int32_t> hh1_tone, cv_hh1_tone;
            atomic<int32_t> hh1_decay, cv_hh1_decay;
            atomic<int32_t> hh1_noise, cv_hh1_noise;
            // sectionHpp
        };
    }
}

