#include "ctagSoundProcessorDrumRackHH2.hpp"

using namespace CTAG::SP;

// TODOs: fx return before compressor, stereo panning with delay -> when panned right, levels are lower, metallic sound of reverb.

void ctagSoundProcessorDrumRackHH2::Process(const ProcessData& data){
    const float maxFXSendLevelDly {4.f};
    const float maxFXSendLevelRev {2.f};
    
    // HiHat 2
    MK_BOOL_PAR(bHH2Mute, hh2_mute)
    MK_BOOL_PAR(bHH2Trig, hh2_trigger)
    if (bHH2Trig != hh2_trig_prev){
        hh2_trig_prev = bHH2Trig;
    }
    else{
        bHH2Trig = false;
    }

    MK_FLT_PAR_ABS(fHH2Lev, hh2_lev, 4095.f, 2.f)
    fHH2Lev *= fHH2Lev;
    MK_FLT_PAR_ABS_PAN(fHH2Pan, hh2_pan, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fHH2FX1Send, hh2_fx1, 4095.f, maxFXSendLevelDly)
    fHH2FX1Send *= fHH2FX1Send;
    MK_FLT_PAR_ABS(fHH2FX2Send, hh2_fx2, 4095.f, maxFXSendLevelRev)
    fHH2FX2Send *= fHH2FX2Send;

    if (bHH2Mute || fHH2Lev < 0.0001f) {
        memset(data.buf, 0, 32 * 2 * sizeof(float));
        return;
    }

    MK_FLT_PAR_ABS(fHH2Accent, hh2_accent, 4095.f, 1.f)
    MK_FLT_PAR_ABS_MIN_MAX(fHH2F0, hh2_f0, 4095.f, .00001f, .1f)
    MK_FLT_PAR_ABS(fHH2Tone, hh2_tone, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fHH2Decay, hh2_decay, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fHH2Noise, hh2_noise, 4095.f, 1.f)
    hh2.Render(
        false,
        bHH2Trig,
        fHH2Accent,
        fHH2F0,
        fHH2Tone,
        fHH2Decay,
        fHH2Noise,
        temp1_,
        temp2_,
        hh2_out,
        32);

    float lev_l = (1.f - fHH2Pan) * fHH2Lev;
    float lev_r = fHH2Pan * fHH2Lev;

    for (int i = 0; i < 32; i++) {
        data.buf[i * 2 + 0] = hh2_out[i] * lev_l;
        data.buf[i * 2 + 1] = hh2_out[i] * lev_r;
    }

    if (fHH2FX1Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus1[i * 2 + 0] += hh2_out[i] * lev_l * fHH2FX1Send;
            data.fxbus1[i * 2 + 1] += hh2_out[i] * lev_r * fHH2FX1Send;
        }
    }

    if (fHH2FX2Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus2[i * 2 + 0] += hh2_out[i] * lev_l * fHH2FX2Send;
            data.fxbus2[i * 2 + 1] += hh2_out[i] * lev_r * fHH2FX2Send;
        }
    }
}

void ctagSoundProcessorDrumRackHH2::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    hh2.Init();

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorDrumRackHH2::~ctagSoundProcessorDrumRackHH2(){
    // no explicit freeing for blockMem needed, done by ctagSPAllocator
    // explicit free is only needed when using heap_caps_malloc() with MALLOC_CAPS_SPIRAM
}

void ctagSoundProcessorDrumRackHH2::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("hh2_trigger", [&](const int val){ hh2_trigger = val;});
	pMapTrig.emplace("hh2_trigger", [&](const int val){ trig_hh2_trigger = val;});
	pMapPar.emplace("hh2_mute", [&](const int val){ hh2_mute = val;});
	pMapTrig.emplace("hh2_mute", [&](const int val){ trig_hh2_mute = val;});
	pMapPar.emplace("hh2_lev", [&](const int val){ hh2_lev = val;});
	pMapCv.emplace("hh2_lev", [&](const int val){ cv_hh2_lev = val;});
	pMapPar.emplace("hh2_pan", [&](const int val){ hh2_pan = val;});
	pMapCv.emplace("hh2_pan", [&](const int val){ cv_hh2_pan = val;});
	pMapPar.emplace("hh2_fx1", [&](const int val){ hh2_fx1 = val;});
	pMapCv.emplace("hh2_fx1", [&](const int val){ cv_hh2_fx1 = val;});
	pMapPar.emplace("hh2_fx2", [&](const int val){ hh2_fx2 = val;});
	pMapCv.emplace("hh2_fx2", [&](const int val){ cv_hh2_fx2 = val;});
	pMapPar.emplace("hh2_accent", [&](const int val){ hh2_accent = val;});
	pMapCv.emplace("hh2_accent", [&](const int val){ cv_hh2_accent = val;});
	pMapPar.emplace("hh2_f0", [&](const int val){ hh2_f0 = val;});
	pMapCv.emplace("hh2_f0", [&](const int val){ cv_hh2_f0 = val;});
	pMapPar.emplace("hh2_tone", [&](const int val){ hh2_tone = val;});
	pMapCv.emplace("hh2_tone", [&](const int val){ cv_hh2_tone = val;});
	pMapPar.emplace("hh2_decay", [&](const int val){ hh2_decay = val;});
	pMapCv.emplace("hh2_decay", [&](const int val){ cv_hh2_decay = val;});
	pMapPar.emplace("hh2_noise", [&](const int val){ hh2_noise = val;});
	pMapCv.emplace("hh2_noise", [&](const int val){ cv_hh2_noise = val;});
	isStereo = false;
	id = "DrumRackHH2";
	// sectionCpp0
}
