#include "ctagSoundProcessorDrumRackSampler.hpp"

using namespace CTAG::SP;

// TODOs: fx return before compressor, stereo panning with delay -> when panned right, levels are lower, metallic sound of reverb.

CTAG::SP::HELPERS::ctagSampleRom ctagSoundProcessorDrumRackSampler::sampleRom;

void ctagSoundProcessorDrumRackSampler::Process(const ProcessData& data){
    const float maxFXSendLevelDly {4.f};
    const float maxFXSendLevelRev {2.f};

    // Rompler
    uint32_t firstNonWtSlice = sampleRom.GetFirstNonWaveTableSlice();
    float fS1Lev = 0.f, fS1Pan = 0.f;
    MK_BOOL_PAR(bMuteS1, s1_mute)
    MK_FLT_PAR_ABS(fS1FX1Send, s1_fx1, 4095.f, maxFXSendLevelDly)
    fS1FX1Send *= fS1FX1Send;
    MK_FLT_PAR_ABS(fS1FX2Send, s1_fx2, 4095.f, maxFXSendLevelRev)
    fS1FX2Send *= fS1FX2Send;

    if (bMuteS1 || fS1Lev < 0.0001f) {
        memset(data.buf, 0, 32 * 2 * sizeof(float));
        return;
    }

    MK_BOOL_PAR(bGateS1, s1_gate)
    rompler[0].params.gate = bGateS1;
    fS1Lev = s1_lev / 4095.f * 1.5f;
    if (cv_s1_lev != -1) fS1Lev += fabsf(data.cv[cv_s1_lev]);
    fS1Lev *= fS1Lev;
    fS1Pan = (s1_pan / 4095.f + 1.f) / 2.f * 1.f;
    if (cv_s1_pan != -1) fS1Pan = fabsf(data.cv[cv_s1_pan]) * 1.f;
    float fS1Speed = s1_speed / 4095.f * 2.f;
    if (cv_s1_speed != -1) fS1Speed += data.cv[cv_s1_speed] * 2.f;
    CONSTRAIN(fS1Speed, -2.f, 2.f)
    rompler[0].params.playbackSpeed = fS1Speed;
    float fS1Pitch = s1_pitch;
    if (cv_s1_pitch != -1){
        fS1Pitch += data.cv[cv_s1_pitch] * 12.f * 5.f;
    }
    rompler[0].params.pitch = fS1Pitch;
    MK_INT_PAR_ABS(iS1Bank, s1_bank, 32.f)
    CONSTRAIN(iS1Bank, 0, 31)
    MK_INT_PAR_ABS(iS1Slice, s1_slice, 32.f)
    CONSTRAIN(iS1Slice, 0, 31)
    iS1Slice = iS1Bank * 32 + iS1Slice + firstNonWtSlice;
    rompler[0].params.slice = iS1Slice;
    MK_FLT_PAR_ABS(fS1Start, s1_start, 4095.f, 1.f)
    rompler[0].params.startOffsetRelative = fS1Start;
    MK_FLT_PAR_ABS(fS1Length, s1_end, 4095.f, 1.f)
    rompler[0].params.lengthRelative = fS1Length;
    MK_FLT_PAR_ABS(fS1LoopPos, s1_lp_pos, 4095.f, 1.f)
    rompler[0].params.loopMarker = fS1LoopPos;
    MK_BOOL_PAR(bS1Loop, s1_lp)
    rompler[0].params.loop = bS1Loop;
    MK_BOOL_PAR(bS1LoopPipo, s1_lp_pp)
    rompler[0].params.loopPiPo = bS1LoopPipo;
    MK_FLT_PAR_ABS(fS1Attack, s1_atk, 4095.f, 2.f)
    rompler[0].params.a = fS1Attack;
    MK_FLT_PAR_ABS(fS1Decay, s1_dcy, 4095.f, 50.f)
    rompler[0].params.d = fS1Decay;
    MK_FLT_PAR_ABS_SFT(fS1EGFM, s1_eg2fm, 4095.f, 12.f)
    rompler[0].params.egFM = fS1EGFM;
    MK_INT_PAR_ABS(iS1Brr, s1_brr, 16)
    CONSTRAIN(iS1Brr, 0, 14)
    rompler[0].params.bitReduction = iS1Brr;
    // filter params
    MK_FLT_PAR_ABS(fS1Cut, s1_fc, 4095.f, 1.f)
    rompler[0].params.cutoff = fS1Cut;
    MK_FLT_PAR_ABS(fS1Reso, s1_fq, 4095.f, 10.f)
    rompler[0].params.resonance = fS1Reso;
    MK_INT_PAR_ABS(iS1FType, s1_ft, 4.f)
    CONSTRAIN(iS1FType, 0, 3);
    rompler[0].params.filterType = static_cast<CTAG::SYNTHESIS::RomplerVoiceMinimal::FilterType>(iS1FType);
    rompler[0].Process(s1_out, 32);
    // data_ptrs[9] = s1_out;
    memcpy(data.buf, s1_out, 32 * sizeof(float));

    float lev_l = (1.f - fS1Pan) * fS1Lev;
    float lev_r = fS1Pan * fS1Lev;

    for (int i = 0; i < 32; i++) {
        data.buf[i * 2 + 0] = s1_out[i] * lev_l;
        data.buf[i * 2 + 1] = s1_out[i] * lev_r;
    }

    if (fS1FX1Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus1[i * 2 + 0] += s1_out[i] * lev_l * fS1FX1Send;
            data.fxbus1[i * 2 + 1] += s1_out[i] * lev_r * fS1FX1Send;
        }
    }

    if (fS1FX2Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus2[i * 2 + 0] += s1_out[i] * lev_l * fS1FX2Send;
            data.fxbus2[i * 2 + 1] += s1_out[i] * lev_r * fS1FX2Send;
        }
    }
}

void ctagSoundProcessorDrumRackSampler::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    sampleRom.BufferInSPIRAM();
    std::fill_n(silence, 32, 0.f);

    // init romplers
    for (auto& r : rompler){
        r.Init(44100.f);
    }

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorDrumRackSampler::~ctagSoundProcessorDrumRackSampler(){
    // no explicit freeing for blockMem needed, done by ctagSPAllocator
    // explicit free is only needed when using heap_caps_malloc() with MALLOC_CAPS_SPIRAM
}

void ctagSoundProcessorDrumRackSampler::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("s1_gate", [&](const int val){ s1_gate = val;});
	pMapTrig.emplace("s1_gate", [&](const int val){ trig_s1_gate = val;});
	pMapPar.emplace("s1_mute", [&](const int val){ s1_mute = val;});
	pMapTrig.emplace("s1_mute", [&](const int val){ trig_s1_mute = val;});
	pMapPar.emplace("s1_lev", [&](const int val){ s1_lev = val;});
	pMapCv.emplace("s1_lev", [&](const int val){ cv_s1_lev = val;});
	pMapPar.emplace("s1_pan", [&](const int val){ s1_pan = val;});
	pMapCv.emplace("s1_pan", [&](const int val){ cv_s1_pan = val;});
	pMapPar.emplace("s1_fx1", [&](const int val){ s1_fx1 = val;});
	pMapCv.emplace("s1_fx1", [&](const int val){ cv_s1_fx1 = val;});
	pMapPar.emplace("s1_fx2", [&](const int val){ s1_fx2 = val;});
	pMapCv.emplace("s1_fx2", [&](const int val){ cv_s1_fx2 = val;});
	pMapPar.emplace("s1_speed", [&](const int val){ s1_speed = val;});
	pMapCv.emplace("s1_speed", [&](const int val){ cv_s1_speed = val;});
	pMapPar.emplace("s1_pitch", [&](const int val){ s1_pitch = val;});
	pMapCv.emplace("s1_pitch", [&](const int val){ cv_s1_pitch = val;});
	pMapPar.emplace("s1_bank", [&](const int val){ s1_bank = val;});
	pMapCv.emplace("s1_bank", [&](const int val){ cv_s1_bank = val;});
	pMapPar.emplace("s1_slice", [&](const int val){ s1_slice = val;});
	pMapCv.emplace("s1_slice", [&](const int val){ cv_s1_slice = val;});
	pMapPar.emplace("s1_start", [&](const int val){ s1_start = val;});
	pMapCv.emplace("s1_start", [&](const int val){ cv_s1_start = val;});
	pMapPar.emplace("s1_end", [&](const int val){ s1_end = val;});
	pMapCv.emplace("s1_end", [&](const int val){ cv_s1_end = val;});
	pMapPar.emplace("s1_lp", [&](const int val){ s1_lp = val;});
	pMapTrig.emplace("s1_lp", [&](const int val){ trig_s1_lp = val;});
	pMapPar.emplace("s1_lp_pp", [&](const int val){ s1_lp_pp = val;});
	pMapTrig.emplace("s1_lp_pp", [&](const int val){ trig_s1_lp_pp = val;});
	pMapPar.emplace("s1_lp_pos", [&](const int val){ s1_lp_pos = val;});
	pMapCv.emplace("s1_lp_pos", [&](const int val){ cv_s1_lp_pos = val;});
	pMapPar.emplace("s1_atk", [&](const int val){ s1_atk = val;});
	pMapCv.emplace("s1_atk", [&](const int val){ cv_s1_atk = val;});
	pMapPar.emplace("s1_dcy", [&](const int val){ s1_dcy = val;});
	pMapCv.emplace("s1_dcy", [&](const int val){ cv_s1_dcy = val;});
	pMapPar.emplace("s1_eg2fm", [&](const int val){ s1_eg2fm = val;});
	pMapCv.emplace("s1_eg2fm", [&](const int val){ cv_s1_eg2fm = val;});
	pMapPar.emplace("s1_brr", [&](const int val){ s1_brr = val;});
	pMapCv.emplace("s1_brr", [&](const int val){ cv_s1_brr = val;});
	pMapPar.emplace("s1_ft", [&](const int val){ s1_ft = val;});
	pMapCv.emplace("s1_ft", [&](const int val){ cv_s1_ft = val;});
	pMapPar.emplace("s1_fc", [&](const int val){ s1_fc = val;});
	pMapCv.emplace("s1_fc", [&](const int val){ cv_s1_fc = val;});
	pMapPar.emplace("s1_fq", [&](const int val){ s1_fq = val;});
	pMapCv.emplace("s1_fq", [&](const int val){ cv_s1_fq = val;});
	isStereo = true;
	id = "DrumRackSampler";
	// sectionCpp0
}
