#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackHH2 : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init() override;
            virtual ~ctagSoundProcessorDrumRackHH2();

        private:
            virtual void knowYourself() override;

            plaits::HiHat<plaits::RingModNoise, plaits::LinearVCA, false, true> hh2;
            float hh2_out[32];
            float temp1_[32];
            float temp2_[32];
            bool hh2_trig_prev {false};

            // rompler
            CTAG::SYNTHESIS::RomplerVoiceMinimal rompler[4];
            CTAG::SP::HELPERS::ctagSampleRom sampleRom;


            // private attributes could go here
            // autogenerated code here
            // sectionHpp
            atomic<int32_t> hh2_trigger, trig_hh2_trigger;
            atomic<int32_t> hh2_mute, trig_hh2_mute;
            atomic<int32_t> hh2_lev, cv_hh2_lev;
            atomic<int32_t> hh2_pan, cv_hh2_pan;
            atomic<int32_t> hh2_fx1, cv_hh2_fx1;
            atomic<int32_t> hh2_fx2, cv_hh2_fx2;
            atomic<int32_t> hh2_accent, cv_hh2_accent;
            atomic<int32_t> hh2_f0, cv_hh2_f0;
            atomic<int32_t> hh2_tone, cv_hh2_tone;
            atomic<int32_t> hh2_decay, cv_hh2_decay;
            atomic<int32_t> hh2_noise, cv_hh2_noise;
            // sectionHpp
        };
    }
}

