#include "ctagSoundProcessorDrumRackHH1.hpp"

using namespace CTAG::SP;

// TODOs: fx return before compressor, stereo panning with delay -> when panned right, levels are lower, metallic sound of reverb.

void ctagSoundProcessorDrumRackHH1::Process(const ProcessData& data){
    const float maxFXSendLevelDly {4.f};
    const float maxFXSendLevelRev {2.f};

    // HiHat 1
    MK_BOOL_PAR(bHH1Mute, hh1_mute)
    MK_BOOL_PAR(bHH1Trig, hh1_trigger)
    if (bHH1Trig != hh1_trig_prev){
        hh1_trig_prev = bHH1Trig;
    }
    else{
        bHH1Trig = false;
    }

    MK_FLT_PAR_ABS(fHH1Lev, hh1_lev, 4095.f, 2.f)
    fHH1Lev *= fHH1Lev;
    MK_FLT_PAR_ABS_PAN(fHH1Pan, hh1_pan, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fHH1FX1Send, hh1_fx1, 4095.f, maxFXSendLevelDly)
    fHH1FX1Send *= fHH1FX1Send;
    MK_FLT_PAR_ABS(fHH1FX2Send, hh1_fx2, 4095.f, maxFXSendLevelRev)
    fHH1FX2Send *= fHH1FX2Send;

    if (bHH1Mute || fHH1Lev < 0.0001f) {
        memset(data.buf, 0, 32 * 2 * sizeof(float));
        return;
    }


    MK_FLT_PAR_ABS(fHH1Accent, hh1_accent, 4095.f, 1.f)
    MK_FLT_PAR_ABS_MIN_MAX(fHH1F0, hh1_f0, 4095.f, 0.0005f, 0.1f)
    MK_FLT_PAR_ABS(fHH1Tone, hh1_tone, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fHH1Decay, hh1_decay, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fHH1Noise, hh1_noise, 4095.f, 1.f)
    hh1.Render(
        false,
        bHH1Trig,
        fHH1Accent,
        fHH1F0,
        fHH1Tone,
        fHH1Decay,
        fHH1Noise,
        temp1_,
        temp2_,
        hh1_out,
        32);
 

    float lev_l = (1.f - fHH1Pan) * fHH1Lev;
    float lev_r = fHH1Pan * fHH1Lev;

    for (int i = 0; i < 32; i++) {
        data.buf[i * 2 + 0] = hh1_out[i] * lev_l;
        data.buf[i * 2 + 1] = hh1_out[i] * lev_r;
    }

    if (fHH1FX1Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus1[i * 2 + 0] += hh1_out[i] * lev_l * fHH1FX1Send;
            data.fxbus1[i * 2 + 1] += hh1_out[i] * lev_r * fHH1FX1Send;
        }
    }

    if (fHH1FX2Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus2[i * 2 + 0] += hh1_out[i] * lev_l * fHH1FX2Send;
            data.fxbus2[i * 2 + 1] += hh1_out[i] * lev_r * fHH1FX2Send;
        }
    }
}

void ctagSoundProcessorDrumRackHH1::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    hh1.Init();

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorDrumRackHH1::~ctagSoundProcessorDrumRackHH1(){
    // no explicit freeing for blockMem needed, done by ctagSPAllocator
    // explicit free is only needed when using heap_caps_malloc() with MALLOC_CAPS_SPIRAM
}

void ctagSoundProcessorDrumRackHH1::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("hh1_trigger", [&](const int val){ hh1_trigger = val;});
	pMapTrig.emplace("hh1_trigger", [&](const int val){ trig_hh1_trigger = val;});
	pMapPar.emplace("hh1_mute", [&](const int val){ hh1_mute = val;});
	pMapTrig.emplace("hh1_mute", [&](const int val){ trig_hh1_mute = val;});
	pMapPar.emplace("hh1_lev", [&](const int val){ hh1_lev = val;});
	pMapCv.emplace("hh1_lev", [&](const int val){ cv_hh1_lev = val;});
	pMapPar.emplace("hh1_pan", [&](const int val){ hh1_pan = val;});
	pMapCv.emplace("hh1_pan", [&](const int val){ cv_hh1_pan = val;});
	pMapPar.emplace("hh1_fx1", [&](const int val){ hh1_fx1 = val;});
	pMapCv.emplace("hh1_fx1", [&](const int val){ cv_hh1_fx1 = val;});
	pMapPar.emplace("hh1_fx2", [&](const int val){ hh1_fx2 = val;});
	pMapCv.emplace("hh1_fx2", [&](const int val){ cv_hh1_fx2 = val;});
	pMapPar.emplace("hh1_accent", [&](const int val){ hh1_accent = val;});
	pMapCv.emplace("hh1_accent", [&](const int val){ cv_hh1_accent = val;});
	pMapPar.emplace("hh1_f0", [&](const int val){ hh1_f0 = val;});
	pMapCv.emplace("hh1_f0", [&](const int val){ cv_hh1_f0 = val;});
	pMapPar.emplace("hh1_tone", [&](const int val){ hh1_tone = val;});
	pMapCv.emplace("hh1_tone", [&](const int val){ cv_hh1_tone = val;});
	pMapPar.emplace("hh1_decay", [&](const int val){ hh1_decay = val;});
	pMapCv.emplace("hh1_decay", [&](const int val){ cv_hh1_decay = val;});
	pMapPar.emplace("hh1_noise", [&](const int val){ hh1_noise = val;});
	pMapCv.emplace("hh1_noise", [&](const int val){ cv_hh1_noise = val;});
	isStereo = true;
	id = "DrumRackHH1";
	// sectionCpp0
}
