#include "ctagSoundProcessorDrumRackAB.hpp"

using namespace CTAG::SP;

void ctagSoundProcessorDrumRackAB::Process(const ProcessData& data){
    const float maxFXSendLevelDly {4.f};
    const float maxFXSendLevelRev {2.f};

    // Analog Bass Drum
    MK_BOOL_PAR(bABMute, ab_mute)
    MK_BOOL_PAR(bABTrig, ab_trigger)
    if (bABTrig != abd_trig_prev){
        abd_trig_prev = bABTrig;
    }
    else{
        bABTrig = false;
    }

    MK_FLT_PAR_ABS(fABLev, ab_lev, 4095.f, 2.f)
    fABLev *= fABLev;
    MK_FLT_PAR_ABS_PAN(fABPan, ab_pan, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fABFX1Send, ab_fx1, 4095.f, maxFXSendLevelDly)
    fABFX1Send *= fABFX1Send;
    MK_FLT_PAR_ABS(fABFX2Send, ab_fx2, 4095.f, maxFXSendLevelRev)
    fABFX2Send *= fABFX2Send;

    if (bABMute || fABLev < 0.0001f) {
        memset(data.buf, 0, 32 * sizeof(float));
        return;
    }

    MK_FLT_PAR_ABS(fABAccent, ab_accent, 4095.f, 1.f)
    MK_FLT_PAR_ABS_MIN_MAX(fABF0, ab_f0, 4095.f, 0.0001f, 0.01f)
    MK_FLT_PAR_ABS(fABTone, ab_tone, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fABDecay, ab_decay, 4095.f, 1.f)
    MK_FLT_PAR_ABS_MIN_MAX(fABAfm, ab_a_fm, 4095.f, 0.f, 100.f)
    MK_FLT_PAR_ABS_MIN_MAX(fABSfm, ab_s_fm, 4095.f, 0.f, 100.f)
    abd.Render(
        false,
        bABTrig,
        fABAccent,
        fABF0,
        fABTone,
        fABDecay,
        fABAfm,
        fABSfm,
        abd_out,
        32);

    float lev_l = (1.f - fABPan) * fABLev;
    float lev_r = fABPan * fABLev;

    for (int i = 0; i < 32; i++) {
        data.buf[i * 2 + 0] = abd_out[i] * lev_l;
        data.buf[i * 2 + 1] = abd_out[i] * lev_r;
    }

    if (fABFX1Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus1[i * 2 + 0] += abd_out[i] * lev_l * fABFX1Send;
            data.fxbus1[i * 2 + 1] += abd_out[i] * lev_r * fABFX1Send;
        }
    }

    if (fABFX2Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus2[i * 2 + 0] += abd_out[i] * lev_l * fABFX2Send;
            data.fxbus2[i * 2 + 1] += abd_out[i] * lev_r * fABFX2Send;
        }
    }
}

void ctagSoundProcessorDrumRackAB::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    abd.Init();

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorDrumRackAB::~ctagSoundProcessorDrumRackAB(){
    // no explicit freeing for blockMem needed, done by ctagSPAllocator
    // explicit free is only needed when using heap_caps_malloc() with MALLOC_CAPS_SPIRAM
}

void ctagSoundProcessorDrumRackAB::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("ab_trigger", [&](const int val){ ab_trigger = val;});
	pMapTrig.emplace("ab_trigger", [&](const int val){ trig_ab_trigger = val;});
	pMapPar.emplace("ab_mute", [&](const int val){ ab_mute = val;});
	pMapTrig.emplace("ab_mute", [&](const int val){ trig_ab_mute = val;});
	pMapPar.emplace("ab_lev", [&](const int val){ ab_lev = val;});
	pMapCv.emplace("ab_lev", [&](const int val){ cv_ab_lev = val;});
	pMapPar.emplace("ab_pan", [&](const int val){ ab_pan = val;});
	pMapCv.emplace("ab_pan", [&](const int val){ cv_ab_pan = val;});
	pMapPar.emplace("ab_fx1", [&](const int val){ ab_fx1 = val;});
	pMapCv.emplace("ab_fx1", [&](const int val){ cv_ab_fx1 = val;});
	pMapPar.emplace("ab_fx2", [&](const int val){ ab_fx2 = val;});
	pMapCv.emplace("ab_fx2", [&](const int val){ cv_ab_fx2 = val;});
	pMapPar.emplace("ab_accent", [&](const int val){ ab_accent = val;});
	pMapCv.emplace("ab_accent", [&](const int val){ cv_ab_accent = val;});
	pMapPar.emplace("ab_f0", [&](const int val){ ab_f0 = val;});
	pMapCv.emplace("ab_f0", [&](const int val){ cv_ab_f0 = val;});
	pMapPar.emplace("ab_tone", [&](const int val){ ab_tone = val;});
	pMapCv.emplace("ab_tone", [&](const int val){ cv_ab_tone = val;});
	pMapPar.emplace("ab_decay", [&](const int val){ ab_decay = val;});
	pMapCv.emplace("ab_decay", [&](const int val){ cv_ab_decay = val;});
	pMapPar.emplace("ab_a_fm", [&](const int val){ ab_a_fm = val;});
	pMapCv.emplace("ab_a_fm", [&](const int val){ cv_ab_a_fm = val;});
	pMapPar.emplace("ab_s_fm", [&](const int val){ ab_s_fm = val;});
	pMapCv.emplace("ab_s_fm", [&](const int val){ cv_ab_s_fm = val;});
	isStereo = false;
	id = "DrumRackAB";
	// sectionCpp0
}
