#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackRS : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init() override;
            virtual ~ctagSoundProcessorDrumRackRS();

        private:
            virtual void knowYourself() override;

            // compressor
            chunkware_simple::SimpleComp sumCompressor;
            float fCompMUPGain_pre {0.f};
            float side_l {0.f};
            float side_r {0.f};

        	// own drum models
        	CTAG::SYNTHESIS::Rimshot rs;

        	float rs_out[32];
        	float silence[32];

        	bool rs_trig_prev {false};

            // rompler
            CTAG::SYNTHESIS::RomplerVoiceMinimal rompler[4];
            CTAG::SP::HELPERS::ctagSampleRom sampleRom;


            // private attributes could go here
            // autogenerated code here
            // sectionHpp
	atomic<int32_t> rs_trigger, trig_rs_trigger;
	atomic<int32_t> rs_mute, trig_rs_mute;
	atomic<int32_t> rs_lev, cv_rs_lev;
	atomic<int32_t> rs_pan, cv_rs_pan;
	atomic<int32_t> rs_fx1, cv_rs_fx1;
	atomic<int32_t> rs_fx2, cv_rs_fx2;
	atomic<int32_t> rs_accent, cv_rs_accent;
	atomic<int32_t> rs_f0, cv_rs_f0;
	atomic<int32_t> rs_tone, cv_rs_tone;
	atomic<int32_t> rs_decay, cv_rs_decay;
	atomic<int32_t> rs_noise, cv_rs_noise;
	// sectionHpp
        };
    }
}

