#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackAB : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init(std::size_t blockSize, void *blockPtr) override;
            virtual ~ctagSoundProcessorDrumRackAB();

        private:
            virtual void knowYourself() override;

            plaits::AnalogBassDrum abd;
            float abd_out[32];
        	float silence[32];
            bool abd_trig_prev {false};

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
            atomic<int32_t> ab_trigger, trig_ab_trigger;
            atomic<int32_t> ab_mute, trig_ab_mute;
            atomic<int32_t> ab_lev, cv_ab_lev;
            atomic<int32_t> ab_pan, cv_ab_pan;
            atomic<int32_t> ab_fx1, cv_ab_fx1;
            atomic<int32_t> ab_fx2, cv_ab_fx2;
            atomic<int32_t> ab_accent, cv_ab_accent;
            atomic<int32_t> ab_f0, cv_ab_f0;
            atomic<int32_t> ab_tone, cv_ab_tone;
            atomic<int32_t> ab_decay, cv_ab_decay;
            atomic<int32_t> ab_a_fm, cv_ab_a_fm;
            atomic<int32_t> ab_s_fm, cv_ab_s_fm; 
            // sectionHpp
        };
    }
}

