#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackFxDelay : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init() override;
            virtual ~ctagSoundProcessorDrumRackFxDelay();

        private:
            virtual void knowYourself() override;

            // delay
            float *delayBuffer_l, *delayBuffer_r;
            const uint32_t delayBufferSizeMax {88200};
            uint32_t writeIndex {0};
            float readPos {0.0f}, readPosFiltered {0.0f};
            float delayOffset {0.0f};
            float duck {0.f};
            float delayTime_ms {0.0f};
            bool pre_sync {false};
            float fDelayTime {0.0f};
            float fSyncTimeStamp {0.0f};
            int32_t timer {0}, pre_timer {0};
            stmlib::OnePole lp_l, hp_l;
            stmlib::OnePole lp_r, hp_r;

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
            atomic<int32_t> fx1_time_ms, cv_fx1_time_ms;
            atomic<int32_t> fx1_sync, trig_fx1_sync;
            atomic<int32_t> fx1_freeze, trig_fx1_freeze;
            atomic<int32_t> fx1_tape_digital, trig_fx1_tape_digital;
            atomic<int32_t> fx1_st_width, cv_fx1_st_width;
            atomic<int32_t> fx1_fx_send, cv_fx1_fx_send;
            atomic<int32_t> fx1_feedback, cv_fx1_feedback;
            atomic<int32_t> fx1_base, cv_fx1_base;
            atomic<int32_t> fx1_width, cv_fx1_width;
            // atomic<int32_t> fx1_amount, cv_fx1_amount;
        };
    }
}

