#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackDS : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init() override;
            virtual ~ctagSoundProcessorDrumRackDS();

        private:
            virtual void knowYourself() override;

            plaits::SyntheticSnareDrum dsd;
            float dsd_out[32];
            bool dsd_trig_prev {false};

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
            atomic<int32_t> ds_trigger, trig_ds_trigger;
            atomic<int32_t> ds_mute, trig_ds_mute;
            atomic<int32_t> ds_lev, cv_ds_lev;
            atomic<int32_t> ds_pan, cv_ds_pan;
            atomic<int32_t> ds_fx1, cv_ds_fx1;
            atomic<int32_t> ds_fx2, cv_ds_fx2;
            atomic<int32_t> ds_accent, cv_ds_accent;
            atomic<int32_t> ds_f0, cv_ds_f0;
            atomic<int32_t> ds_fm_amt, cv_ds_fm_amt;
            atomic<int32_t> ds_decay, cv_ds_decay;
            atomic<int32_t> ds_spy, cv_ds_spy;
            // sectionHpp
        };
    }
}

