#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackFxMaster : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init() override;
            virtual ~ctagSoundProcessorDrumRackFxMaster();

        private:
            virtual void knowYourself() override;

            // compressor
            chunkware_simple::SimpleComp sumCompressor;
            float fCompMUPGain_pre {0.f};
            float side_l {0.f};
            float side_r {0.f};

        	float silence[32];

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
			atomic<int32_t> c_thres, cv_c_thres;
			atomic<int32_t> c_ratio, cv_c_ratio;
			atomic<int32_t> c_atk, cv_c_atk;
			atomic<int32_t> c_rel, cv_c_rel;
			atomic<int32_t> c_lpf, trig_c_lpf;
			atomic<int32_t> c_gain, cv_c_gain;
			atomic<int32_t> c_mix, cv_c_mix;
			atomic<int32_t> c_dly_level, cv_c_dly_level;
			atomic<int32_t> c_rev_level, cv_c_rev_level;
			atomic<int32_t> sum_mute, trig_sum_mute;
			atomic<int32_t> sum_lev, cv_sum_lev;
			atomic<int32_t> fx1_amount, cv_fx1_amount;
			atomic<int32_t> fx2_amount, cv_fx2_amount;
			// sectionHpp
        };
    }
}

