#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackDB : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init() override;
            virtual ~ctagSoundProcessorDrumRackDB();

        private:
            virtual void knowYourself() override;

            plaits::SyntheticBassDrum dbd;
            float dbd_out[32];
            bool dbd_trig_prev {false};

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
            atomic<int32_t> db_trigger, trig_db_trigger;
            atomic<int32_t> db_mute, trig_db_mute;
            atomic<int32_t> db_lev, cv_db_lev;
            atomic<int32_t> db_pan, cv_db_pan;
            atomic<int32_t> db_fx1, cv_db_fx1;
            atomic<int32_t> db_fx2, cv_db_fx2;
            atomic<int32_t> db_accent, cv_db_accent;
            atomic<int32_t> db_f0, cv_db_f0;
            atomic<int32_t> db_tone, cv_db_tone;
            atomic<int32_t> db_decay, cv_db_decay;
            atomic<int32_t> db_dirty, cv_db_dirty;
            atomic<int32_t> db_fm_env, cv_db_fm_env;
            atomic<int32_t> db_fm_dcy, cv_db_fm_dcy;
            // sectionHpp
        };
    }
}

