#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackFxAmp : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init(std::size_t blockSize, void *blockPtr) override;
            virtual ~ctagSoundProcessorDrumRackFxAmp();

        private:
            virtual void knowYourself() override;

			float temp1_[32];
            float temp2_[32];
        	float silence[32];

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
			atomic<int32_t> sum_mute, trig_sum_mute;
			atomic<int32_t> sum_lev, cv_sum_lev;
			atomic<int32_t> fx1_amount, cv_fx1_amount;
			atomic<int32_t> fx2_amount, cv_fx2_amount;
			// sectionHpp
        };
    }
}

