#include "ctagSoundProcessorDrumRackFxReverb.hpp"

using namespace CTAG::SP;

// TODOs: fx return before compressor, stereo panning with delay -> when panned right, levels are lower, metallic sound of reverb.

void ctagSoundProcessorDrumRackFxReverb::Process(const ProcessData& data){
    const float maxFXSendLevelDly {4.f};
    const float maxFXSendLevelRev {2.f};

    // reverb
    MK_FLT_PAR_ABS(fRevTime, fx2_time, 4095.f, 1.f)
    // MK_FLT_PAR_ABS(fRevAmount, fx2_amount, 4095.f, 2.f)
    MK_FLT_PAR_ABS(fReverbLPF, fx2_lp, 4095.f, 1.f)
    reverb.set_time(fRevTime);
    reverb.set_lp(fReverbLPF);
}

void ctagSoundProcessorDrumRackFxReverb::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    blockSize = ctagSPAllocator::GetRemainingBlockMem();
    blockPtr = ctagSPAllocator::AllocateBlockMem(32768 * 4);

    // reverb
    assert(blockSize >= 32768 * 4);
    reverb.Init((float*)blockPtr); // requires 32768*4 bytes = 128KB
    reverb.Clear();
    blockPtr = static_cast<void*>(static_cast<uint8_t*>(blockPtr) + 32768 * 4);
    blockSize -= 32768 * 4;
    reverb.set_diffusion(0.7f);
    reverb.set_input_gain(.5f); // left and right are summed
    reverb.set_amount(1.f);
    reverb.set_lp(0.5f);
    reverb.set_time(0.4f);

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorDrumRackFxReverb::~ctagSoundProcessorDrumRackFxReverb(){
    // no explicit freeing for blockMem needed, done by ctagSPAllocator
    // explicit free is only needed when using heap_caps_malloc() with MALLOC_CAPS_SPIRAM
    ctagSPAllocator::ReleaseBlockMem(blockPtr);
}

void ctagSoundProcessorDrumRackFxReverb::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("fx2_time", [&](const int val){ fx2_time = val;});
	pMapCv.emplace("fx2_time", [&](const int val){ cv_fx2_time = val;});
	pMapPar.emplace("fx2_lp", [&](const int val){ fx2_lp = val;});
	pMapCv.emplace("fx2_lp", [&](const int val){ cv_fx2_lp = val;});
	isStereo = true;
	id = "DrumRackFxReverb";
	// sectionCpp0
}
