#include "ctagSoundProcessorDrumRackCL.hpp"

using namespace CTAG::SP;

void ctagSoundProcessorDrumRackCL::Process(const ProcessData& data){
    const float maxFXSendLevelDly {4.f};
    const float maxFXSendLevelRev {2.f};

    // Clap
    MK_BOOL_PAR(bCLMute, cl_mute)
    MK_FLT_PAR_ABS(fCLLev, cl_lev, 4095.f, 2.f)
    fCLLev *= fCLLev;
    MK_FLT_PAR_ABS_PAN(fCLPan, cl_pan, 4095.f, 1.f)
    MK_FLT_PAR_ABS(fCLFX1Send, cl_fx1, 4095.f, maxFXSendLevelDly)
    fCLFX1Send *= fCLFX1Send;
    MK_FLT_PAR_ABS(fCLFX2Send, cl_fx2, 4095.f, maxFXSendLevelRev)
    fCLFX2Send *= fCLFX2Send;

    if (bCLMute || fCLLev < 0.0001f) {
        memset(data.buf, 0, 32 * sizeof(float));
        return;
    }

    MK_FLT_PAR_ABS_MIN_MAX(cl_pitch1_, cl_f0, 4095.f, 350.f, 4000.f)
    MK_FLT_PAR_ABS_MIN_MAX(cl_pitch2_, cl_f0, 4095.f, 300.f, 3000.f)
    MK_FLT_PAR_ABS_MIN_MAX(cl_reso1_, cl_tone, 4095.f, 1.f, 2.5f)
    MK_FLT_PAR_ABS_MIN_MAX(cl_reso2_, cl_tone, 4095.f, 0.75f, 6.5f)
    MK_FLT_PAR_ABS_MIN_MAX(cl_decay1_, cl_decay, 4095.f, 0.05f, 0.3f)
    MK_FLT_PAR_ABS_MIN_MAX(cl_decay2_, cl_decay, 4095.f, 0.05f, 2.f)
    MK_FLT_PAR_ABS_MIN_MAX(cl_scale_attack_, cl_scale, 4095.f, 0.f, 0.1f)
    MK_FLT_PAR_ABS_MIN_MAX(cl_scale_trans, cl_scale, 4095.f, 1.f, 3.f)
    MK_INT_PAR_ABS(cl_trans_, cl_transient, 16)

    cl.params.pitch1 = cl_pitch1_ / 44100.f;
    cl.params.pitch2 = cl_pitch2_ / 44100.f;
    cl.params.reso1 = cl_reso1_;
    cl.params.reso2 = cl_reso2_;
    cl.params.decay1 = cl_decay1_;
    cl.params.decay2 = cl_decay2_;
    cl.params.attack = cl_scale_attack_;
    cl.params.scale = cl_scale_trans;
    cl.params.transient = cl_trans_ % 16;

    MK_BOOL_PAR(bCLTrig, cl_trigger)
    if (bCLTrig != cl_trig_prev && bCLTrig){
        cl_trig_prev = true;
        cl.Trigger();
    }
    else if (!bCLTrig){
        cl_trig_prev = false;
    }

    cl.Process(cl_out, 32);

    float lev_l = (1.f - fCLPan) * fCLLev;
    float lev_r = fCLPan * fCLLev;

    for (int i = 0; i < 32; i++) {
        data.buf[i * 2 + 0] = cl_out[i] * lev_l;
        data.buf[i * 2 + 1] = cl_out[i] * lev_r;
    }

    if (fCLFX1Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus1[i * 2 + 0] += cl_out[i] * lev_l * fCLFX1Send;
            data.fxbus1[i * 2 + 1] += cl_out[i] * lev_r * fCLFX1Send;
        }
    }

    if (fCLFX2Send > 0.0001) {
        for (int i = 0; i < 32; i++) {
            data.fxbus2[i * 2 + 0] += cl_out[i] * lev_l * fCLFX2Send;
            data.fxbus2[i * 2 + 1] += cl_out[i] * lev_r * fCLFX2Send;
        }
    }
}

void ctagSoundProcessorDrumRackCL::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    cl.Init();

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorDrumRackCL::~ctagSoundProcessorDrumRackCL(){
    // no explicit freeing for blockMem needed, done by ctagSPAllocator
    // explicit free is only needed when using heap_caps_malloc() with MALLOC_CAPS_SPIRAM
}

void ctagSoundProcessorDrumRackCL::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("cl_trigger", [&](const int val){ cl_trigger = val;});
	pMapTrig.emplace("cl_trigger", [&](const int val){ trig_cl_trigger = val;});
	pMapPar.emplace("cl_mute", [&](const int val){ cl_mute = val;});
	pMapTrig.emplace("cl_mute", [&](const int val){ trig_cl_mute = val;});
	pMapPar.emplace("cl_lev", [&](const int val){ cl_lev = val;});
	pMapCv.emplace("cl_lev", [&](const int val){ cv_cl_lev = val;});
	pMapPar.emplace("cl_pan", [&](const int val){ cl_pan = val;});
	pMapCv.emplace("cl_pan", [&](const int val){ cv_cl_pan = val;});
	pMapPar.emplace("cl_fx1", [&](const int val){ cl_fx1 = val;});
	pMapCv.emplace("cl_fx1", [&](const int val){ cv_cl_fx1 = val;});
	pMapPar.emplace("cl_fx2", [&](const int val){ cl_fx2 = val;});
	pMapCv.emplace("cl_fx2", [&](const int val){ cv_cl_fx2 = val;});
	pMapPar.emplace("cl_f0", [&](const int val){ cl_f0 = val;});
	pMapCv.emplace("cl_f0", [&](const int val){ cv_cl_f0 = val;});
	pMapPar.emplace("cl_tone", [&](const int val){ cl_tone = val;});
	pMapCv.emplace("cl_tone", [&](const int val){ cv_cl_tone = val;});
	pMapPar.emplace("cl_decay", [&](const int val){ cl_decay = val;});
	pMapCv.emplace("cl_decay", [&](const int val){ cv_cl_decay = val;});
	pMapPar.emplace("cl_scale", [&](const int val){ cl_scale = val;});
	pMapCv.emplace("cl_scale", [&](const int val){ cv_cl_scale = val;});
	pMapPar.emplace("cl_transient", [&](const int val){ cl_transient = val;});
	pMapCv.emplace("cl_transient", [&](const int val){ cv_cl_transient = val;});
	isStereo = false;
	id = "DrumRackCL";
	// sectionCpp0
}
