#include "ctagSoundProcessorDrumRackFxAmp.hpp"

using namespace CTAG::SP;

void ctagSoundProcessorDrumRackFxAmp::Process(const ProcessData& data){
    MK_BOOL_PAR(bSumMute, sum_mute)

    MK_FLT_PAR_ABS(fSumLev, sum_lev, 4095.f, 2.f)
    fSumLev *= fSumLev;
    MK_FLT_PAR_ABS_PAN(fSumPan, sum_pan, 4095.f, 1.f)

    if (bSumMute || fSumLev < 0.0001f) {
        memset(data.buf, 0, 32 * 2 * sizeof(float));
        return;
    }

    float lev_l = (1.f - fSumPan) * fSumLev;
    float lev_r = fSumPan * fSumLev;

    for (int i = 0; i < 32; i++) {
        data.buf[i * 2 + 0] *= lev_l;
        data.buf[i * 2 + 1] *= lev_r;
    }
}

void ctagSoundProcessorDrumRackFxAmp::Init(){
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);

    // check if blockMem is large enough
    // blockMem is used just like larger blocks of heap memory
    // assert(blockSize >= memLen);
    // if memory larger than blockMem is needed, use heap_caps_malloc() instead with MALLOC_CAPS_SPIRAM
}

ctagSoundProcessorDrumRackFxAmp::~ctagSoundProcessorDrumRackFxAmp() {
}

void ctagSoundProcessorDrumRackFxAmp::knowYourself(){
    // autogenerated code here
    // sectionCpp0
	pMapPar.emplace("sum_mute", [&](const int val){ sum_mute = val;});
	pMapTrig.emplace("sum_mute", [&](const int val){ trig_sum_mute = val;});
	pMapPar.emplace("sum_lev", [&](const int val){ sum_lev = val;});
	pMapCv.emplace("sum_lev", [&](const int val){ cv_sum_lev = val;});
	pMapPar.emplace("sum_pan", [&](const int val){ sum_pan = val;});
	pMapCv.emplace("sum_pan", [&](const int val){ cv_sum_pan = val;});
	isStereo = true;
	id = "DrumRackFxAmp";
	// sectionCpp0
}
