#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "plaits/dsp/drums/analog_bass_drum.h"
#include "plaits/dsp/drums/analog_snare_drum.h"
#include "plaits/dsp/drums/synthetic_bass_drum.h"
#include "plaits/dsp/drums/synthetic_snare_drum.h"
#include "plaits/dsp/drums/hi_hat.h"
#include "synthesis/RomplerVoiceMinimal.hpp"
#include "synthesis/Clap.hpp"
#include "synthesis/Rimshot.hpp"
#include "synthesis/FmKick.hpp"
#include "helpers/ctagSampleRom.hpp"
#include "SimpleComp/SimpleComp.h"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorDrumRackFMB : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            // no ctor, use Init() instead, is called from factory after successful creation
            virtual void Init() override;
            virtual ~ctagSoundProcessorDrumRackFMB();

        private:
            virtual void knowYourself() override;

            float fmb_out[32];
            CTAG::SYNTHESIS::FmKick fmb;
            bool fmb_trig_prev {false};

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
            atomic<int32_t> fmb_trigger, trig_fmb_trigger;
            atomic<int32_t> fmb_mute, trig_fmb_mute;
            atomic<int32_t> fmb_lev, cv_fmb_lev;
            atomic<int32_t> fmb_pan, cv_fmb_pan;
            atomic<int32_t> fmb_fx1, cv_fmb_fx1;
            atomic<int32_t> fmb_fx2, cv_fmb_fx2;
            atomic<int32_t> fmb_use_ratio_mode, trig_fmb_use_ratio_mode;
            atomic<int32_t> fmb_mod_env_sync, trig_fmb_mod_env_sync;
            atomic<int32_t> fmb_f_b, cv_fmb_f_b;
            atomic<int32_t> fmb_d_b, cv_fmb_d_b;
            atomic<int32_t> fmb_f_m, cv_fmb_f_m;
            atomic<int32_t> fmb_I, cv_fmb_I;
            atomic<int32_t> fmb_d_m, cv_fmb_d_m;
            atomic<int32_t> fmb_b_m, cv_fmb_b_m;
            atomic<int32_t> fmb_A_f, cv_fmb_A_f;
            atomic<int32_t> fmb_d_f, cv_fmb_d_f;
            // sectionHpp
        };
    }
}

